export const ACTION_TYPES = {
  NUMBERS: {
    SET_DATA: 'SET_NUMBERS_DATA',
    SET_LOADING: 'SET_NUMBERS_LOADING',
    SET_ERROR: 'SET_NUMBERS_ERROR'
  },
  TESTIMONIALS: {
    SET_DATA: 'SET_TESTIMONIALS_DATA',
    SET_LOADING: 'SET_TESTIMONIALS_LOADING',
    SET_ERROR: 'SET_TESTIMONIALS_ERROR'
  },
  HEADER_CAROUSEL: {
    SET_DATA: 'SET_HEADER_CAROUSEL_DATA',
    SET_LOADING: 'SET_HEADER_CAROUSEL_LOADING',
    SET_ERROR: 'SET_HEADER_CAROUSEL_ERROR'
  },
  UPCOMING_EVENTS: {
    SET_DATA: 'SET_UPCOMING_EVENTS_DATA',
    SET_LOADING: 'SET_UPCOMING_EVENTS_LOADING',
    SET_ERROR: 'SET_UPCOMING_EVENTS_ERROR'
  },
  FEATURED_CAUSE: {
    SET_DATA: 'SET_FEATURED_CAUSE_DATA',
    SET_LOADING: 'SET_FEATURED_CAUSE_LOADING',
    SET_ERROR: 'SET_FEATURED_CAUSE_ERROR'
  },
  NEWS_ARTICLES: {
    SET_DATA: 'SET_NEWS_ARTICLES_DATA',
    SET_LOADING: 'SET_NEWS_ARTICLES_LOADING',
    SET_ERROR: 'SET_NEWS_ARTICLES_ERROR'
  },
  ACTIVITIES: {
    SET_DATA: 'SET_ACTIVITIES_DATA',
    SET_LOADING: 'SET_ACTIVITIES_LOADING',
    SET_ERROR: 'SET_ACTIVITIES_ERROR'
  },
  FEATURED_BANNER: {
    SET_DATA: 'SET_FEATURED_BANNER_DATA',
    SET_LOADING: 'SET_FEATURED_BANNER_LOADING',
    SET_ERROR: 'SET_FEATURED_BANNER_ERROR'
  },
  CAUSES: {
    SET_DATA: 'SET_CAUSES_DATA',
    SET_LOADING: 'SET_CAUSES_LOADING',
    SET_ERROR: 'SET_CAUSESS_ERROR'
  },
  WORKSTYLE: {
    SET_DATA: 'SET_WORKSTYLE_DATA',
    SET_LOADING: 'SET_WORKSTYLE_LOADING',
    SET_ERROR: 'SET_WORKSTYLE_ERROR'
  },
  CONTACTINFO: {
    SET_DATA: 'SET_CONTACTINFO_DATA',
    SET_LOADING: 'SET_CONTACTINFO_LOADING',
    SET_ERROR: 'SET_CONTACTINFO_ERROR'
  },
  SOCIAL: {
    SET_DATA: 'SET_SOCIAL_DATA',
    SET_LOADING: 'SET_SOCIAL_LOADING',
    SET_ERROR: 'SET_SOCIAL_ERROR'
  },
  WELCOME: {
    SET_DATA: 'SET_WELCOME_DATA',
    SET_LOADING: 'SET_WELCOME_LOADING',
    SET_ERROR: 'SET_WELCOME_ERROR'
  },
  FOOTER: {
    SET_DATA: 'SET_FOOTER_DATA',
    SET_LOADING: 'SET_FOOTER_LOADING',
    SET_ERROR: 'SET_FOOTER_ERROR'
  },
  PAGES: {
    SET_DATA: 'SET_PAGES_DATA',
    SET_LOADING: 'SET_PAGES_LOADING',
    SET_ERROR: 'SET_PAGES_ERROR'
  },
  ARTICLES: {
    SET_DATA: 'SET_ARTICLES_DATA',
    SET_LOADING: 'SET_ARTICLES_LOADING',
    SET_ERROR: 'SET_ARTICLES_ERROR'
  },
  LOGO: {
    SET_DATA: 'SET_LOGO_DATA',
    SET_LOADING: 'SET_LOGO_LOADING',
    SET_ERROR: 'SET_LOGO_ERROR'
  },
  MAIN_CONTACT: {
    SET_DATA: 'SET_MAIN_CONTACT_DATA',
    SET_LOADING: 'SET_MAIN_CONTACT_LOADING',
    SET_ERROR: 'SET_MAIN_CONTACT_ERROR'
  },
  SPONSERS: {
    SET_DATA: 'SET_SPONSERS_DATA',
    SET_LOADING: 'SET_SPONSERS_LOADING',
    SET_ERROR: 'SET_SPONSERS_ERROR'
  },
  CONTACT_TOP: {
    SET_DATA: 'SET_CONTACT_TOP_DATA',
    SET_LOADING: 'SET_CONTACT_TOP_LOADING',
    SET_ERROR: 'SET_CONTACT_TOP_ERROR'
  }
};
