export const ACTION_TYPES = {
  NUMBERS: {
    SET_DATA: 'SET_NUMBERS_DATA',
    SET_LOADING: 'SET_NUMBERS_LOADING',
    SET_ERROR: 'SET_NUMBERS_ERROR'
  },
  TESTIMONIALS: {
    SET_DATA: 'SET_TESTIMONIALS_DATA',
    SET_LOADING: 'SET_TESTIMONIALS_LOADING',
    SET_ERROR: 'SET_TESTIMONIALS_ERROR'
  },
  ACTIVITIES: {
    SET_DATA: 'SET_ACTIVITIES_DATA',
    SET_LOADING: 'SET_ACTIVITIES_LOADING',
    SET_ERROR: 'SET_ACTIVITIES_ERROR'
  },
  FEATURED_BANNER: {
    SET_DATA: 'SET_FEATURED_BANNER_DATA',
    SET_LOADING: 'SET_FEATURED_BANNER_LOADING',
    SET_ERROR: 'SET_FEATURED_BANNER_ERROR'
  },
  CAUSES: {
    SET_DATA: 'SET_CAUSES_DATA',
    SET_LOADING: 'SET_CAUSES_LOADING',
    SET_ERROR: 'SET_CAUSESS_ERROR'
  },
  WORKSTYLE: {
    SET_DATA: 'SET_WORKSTYLE_DATA',
    SET_LOADING: 'SET_WORKSTYLE_LOADING',
    SET_ERROR: 'SET_WORKSTYLE_ERROR'
  },
  CONTACTINFO: {
    SET_DATA: 'SET_CONTACTINFO_DATA',
    SET_LOADING: 'SET_CONTACTINFO_LOADING',
    SET_ERROR: 'SET_CONTACTINFO_ERROR'
  },
  SOCIAL: {
    SET_DATA: 'SET_SOCIAL_DATA',
    SET_LOADING: 'SET_SOCIAL_LOADING',
    SET_ERROR: 'SET_SOCIAL_ERROR'
  },
  WELCOME: {
    SET_DATA: 'SET_WELCOME_DATA',
    SET_LOADING: 'SET_WELCOME_LOADING',
    SET_ERROR: 'SET_WELCOME_ERROR'
  },
  PAGES: {
    SET_DATA: 'SET_PAGES_DATA',
    SET_LOADING: 'SET_PAGES_LOADING',
    SET_ERROR: 'SET_PAGES_ERROR'
  }
};
