export const ACTION_TYPES = {
  NUMBERS: {
    SET_DATA: 'SET_NUMBERS_DATA',
    SET_LOADING: 'SET_NUMBERS_LOADING',
    SET_ERROR: 'SET_NUMBERS_ERROR'
  },
  TESTIMONIALS: {
    SET_DATA: 'SET_TESTIMONIALS_DATA',
    SET_LOADING: 'SET_TESTIMONIALS_LOADING',
    SET_ERROR: 'SET_TESTIMONIALS_ERROR'
  },
  HEADER_CAROUSEL: {
    SET_DATA: 'SET_HEADER_CAROUSEL_DATA',
    SET_LOADING: 'SET_HEADER_CAROUSEL_LOADING',
    SET_ERROR: 'SET_HEADER_CAROUSEL_ERROR'
  }
};
